import Image from 'next/image';
import Link from 'next/link';
import { publicMedia } from '@/server/files';
export const dynamic='force-dynamic';
import { ArrowUpRight } from 'lucide-react';
import { PageIntro } from '@/components/ui';
export const metadata = { title: 'Through the polar lens' };
const photos = [{ image: 'penguins', title: 'A moment in the white wilderness.', location: 'Two Hummock Island, Antarctica', photographer: 'Derek Oyen', url: 'https://unsplash.com/photos/3Xd5j9-drDA', alt: 'Chinstrap penguins in the snow on Two Hummock Island' }, { image: 'hero', title: 'Where mountains meet the sea.', location: 'Antarctica', photographer: 'DD Wido', url: 'https://unsplash.com/photos/bu183EEgaVY', alt: 'Antarctic snow-covered mountains above a calm ocean' }, { image: 'arctic', title: 'The quiet of the far north.', location: 'Svalbard, Arctic', photographer: 'Fredrik Solli Wandem', url: 'https://unsplash.com/photos/uNnN7IBN9As', alt: 'Snow-covered coastal mountains in Svalbard' }];
export default async function MediaPage() { const published=(await publicMedia()).filter(f=>f.mime.startsWith('image/')); return <main id="main"><PageIntro eyebrow="THROUGH THE POLAR LENS" title="Let the landscape speak." description="A photographic introduction to polar landscapes and wildlife. Independently sourced imagery, with every photographer credited." />{published.length>0&&<section className="container"><span className="eyebrow">FROM THE REVIEWED COLLECTION</span><h2>Photographs with a story.</h2><div className="published-media-grid">{published.map(f=><article className="attachment-card" key={`${f.slug}-${f.id}`}><img className="evidence-image" src={`/api/files/${f.id}?preview=1`} alt={f.attachment.alt} loading="lazy"/><h3>{f.attachment.alt}</h3><p>{f.attachment.credit} · {f.attachment.license}</p><Link className="text-link" href={`/resources/${f.slug}`}>Explore the source <ArrowUpRight size={14}/></Link></article>)}</div></section>}<div className="gallery-grid container">{photos.map(p => <article key={p.image} className="gallery-card"><div className="gallery-photo"><Image src={`/images/${p.image}.jpg`} alt={p.alt} fill sizes="(max-width: 600px) 100vw, 60vw" /></div><h2>{p.title}</h2><p>{p.location} · Photograph by {p.photographer}</p><a href={p.url} target="_blank" rel="noreferrer">View original on Unsplash <ArrowUpRight size={14} /></a></article>)}</div></main>; }
