export type Resource = {
  slug: string; title: string; type: 'Report' | 'Dataset' | 'Publication' | 'Explainer';
  region: 'Arctic' | 'Antarctica' | 'Southern Ocean'; year: number; topic: string;
  summary: string; source: string; sourceName: string; readTime: string;
  attachments?: import('./file-schema').Attachment[];
  image: string; body: string[]; sample: boolean;
};

export const resources: Resource[] = [
  { slug: 'arctic-expedition-report', title: 'A year of discovery in the Arctic', type: 'Report', region: 'Arctic', year: 2024, topic: 'Atmosphere', summary: 'Explore the official Indian Arctic expedition report for 2023–24 and the move toward year-round observations.', source: 'https://www.ncpor.res.in/files/14-Arctic_Expedition-2023-24_Report-Low_Resolution.pdf', sourceName: 'NCPOR • Arctic Expedition Report 2023–24', readTime: 'Source report', image: '/images/arctic.jpg', sample: false, body: ['The Arctic is a place to ask questions about the connections between atmosphere, ice, oceans and living systems. This catalogue entry links to NCPOR’s published Arctic expedition report for 2023–24.', 'Read the original report for expedition details, methods and findings. PolarBridge provides a discovery entry; the linked report remains the authoritative source.'] },
  { slug: 'polar-data-catalogue', title: 'Find the evidence behind polar science', type: 'Dataset', region: 'Antarctica', year: 2026, topic: 'Ocean science', summary: 'A starting point for discovering datasets through the National Polar Data Center’s authoritative catalogue.', source: 'https://npdc.ncpor.res.in/', sourceName: 'NCPOR • National Polar Data Center', readTime: 'Data catalogue', image: '/images/hero.jpg', sample: false, body: ['The National Polar Data Center provides an authoritative starting point for discovering polar research data. Follow the source link to explore available records and their access conditions.', 'This is a catalogue gateway, not a hosted scientific dataset. Coverage, variables, units, licensing and download options must be checked on each original record. The displayed year indicates when this gateway entry was curated.'] },
  { slug: 'antarctic-research-programme', title: 'Science at the southern edge of the world', type: 'Publication', region: 'Antarctica', year: 2026, topic: 'Climate', summary: 'An introduction to the Indian Antarctic programme and its multidisciplinary research themes.', source: 'https://ncps.ncpor.res.in/expedition/india_antarctica.php', sourceName: 'NCPOR • Indian Antarctic Programme', readTime: 'Programme overview', image: '/images/hero.jpg', sample: false, body: ['Antarctic research connects many disciplines. The official programme overview describes research interests spanning sea ice, aerosols, ozone and the wider climate system.', 'Visit the original programme page to read the institutional overview. This entry is a curated external reference and is not an expedition field report. The displayed year is the catalogue entry year.'] },
  { slug: 'sea-ice-explained', title: 'Small changes in ice. A much bigger story.', type: 'Explainer', region: 'Antarctica', year: 2026, topic: 'Sea ice', summary: 'A gentle introduction to why researchers study sea ice and how observations become scientific questions.', source: 'https://ncps.ncpor.res.in/expedition/india_antarctica.php', sourceName: 'Further reading • NCPOR Antarctic Programme', readTime: '3 min read', image: '/images/hero.jpg', sample: true, body: ['Look at a polar landscape and you might see a still, white world. Researchers see questions: where is the ice, how does it change, and how does it connect with the ocean and atmosphere?', 'A single photograph captures a moment. Repeated observations help researchers compare moments over time. Understanding those comparisons also requires knowing how, when and where measurements were collected.', 'This sample learning article demonstrates how a source-linked explanation could appear. It has not undergone scientific editorial review. Follow the official programme overview for authoritative context.'] },
  { slug: 'arctic-observation-guide', title: 'What does a polar scientist actually observe?', type: 'Explainer', region: 'Arctic', year: 2026, topic: 'Atmosphere', summary: 'Follow the questions that turn a distant landscape into a place of scientific discovery.', source: 'https://www.ncpor.res.in/files/14-Arctic_Expedition-2023-24_Report-Low_Resolution.pdf', sourceName: 'Further reading • NCPOR Arctic Report', readTime: '4 min read', image: '/images/arctic.jpg', sample: true, body: ['A research expedition starts with questions. Observations, careful records and repeatable methods help turn those questions into evidence that other researchers can examine.', 'An expedition report helps readers understand what was studied and how the work was carried out. Start with its overview, then explore the sections that match your interests.', 'This is sample educational copy for the prototype, not a reviewed summary of the linked report. The original report provides the scientific detail.'] },
  { slug: 'southern-ocean-research', title: 'An ocean that connects a continent', type: 'Publication', region: 'Southern Ocean', year: 2026, topic: 'Ocean science', summary: 'Discover the institution behind India’s polar and Southern Ocean research activities.', source: 'https://www.ncpor.res.in/', sourceName: 'NCPOR • Institutional website', readTime: 'Institutional overview', image: '/images/hero.jpg', sample: false, body: ['NCPOR’s institutional website is a starting point for learning about its polar and Southern Ocean research activities.', 'Use the original website to discover programmes, institutional updates and published resources. This entry is an external reference; it does not contain a new dataset or claim to summarize research findings.'] },
];

export const expeditions = [
  { slug: 'antarctica', region: 'Antarctica', eyebrow: 'THE SOUTHERN FRONTIER', title: 'At the edge of the world.', description: 'Explore the research, questions and discoveries that bring us closer to Earth’s southernmost continent.', image: '/images/hero.jpg', coordinate: '90° S · POLAR REGION', source: 'https://ncps.ncpor.res.in/expedition/india_antarctica.php' },
  { slug: 'arctic', region: 'Arctic', eyebrow: 'THE NORTHERN PERSPECTIVE', title: 'A different kind of north.', description: 'Follow India’s Arctic research through expedition reports and a changing northern landscape.', image: '/images/arctic.jpg', coordinate: '90° N · POLAR REGION', source: 'https://www.ncpor.res.in/files/14-Arctic_Expedition-2023-24_Report-Low_Resolution.pdf' },
  { slug: 'southern-ocean', region: 'Southern Ocean', eyebrow: 'BETWEEN ICE AND OCEAN', title: 'Everything is connected.', description: 'An introduction to the ocean surrounding Antarctica and the institution studying its connections.', image: '/images/hero.jpg', coordinate: 'SOUTHERN HEMISPHERE', source: 'https://www.ncpor.res.in/' },
];

export const topics = ['Sea ice', 'Climate', 'Ocean science', 'Atmosphere'];
