import Image from 'next/image';
import { publicMedia } from '@/server/files';
import { notFound } from 'next/navigation';
import { ExternalLink } from 'lucide-react';
import { publicCollection } from '@/server/public-collection';
import { BackLink, ResourceCard, TypeIcon } from '@/components/ui';
import { CopyCitation } from '@/components/copy-citation';

export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const resource = (await publicCollection()).find(r => r.slug === slug); return { title: resource?.title || 'Resource not found', description: resource?.summary }; }
export default async function ResourcePage({ params }: { params: Promise<{ slug: string }> }) {
  const resources = await publicCollection();
  const { slug } = await params; const resource = resources.find(r => r.slug === slug); if (!resource) notFound();
  const files=(await publicMedia()).filter(f=>f.slug===slug);
  const related = resources.filter(r => r.slug !== slug && (r.region === resource.region || r.topic === resource.topic)).slice(0, 3);
  return <main id="main" className="detail-wrap container"><BackLink /><div className="detail-grid"><article className="detail-main"><span className="resource-type"><TypeIcon type={resource.type} />{resource.type}</span><h1>{resource.title}</h1><p className="detail-deck">{resource.summary}</p><div className="detail-actions"><span className="card-meta">{resource.region}<span />{resource.readTime}</span><CopyCitation citation={`${resource.title}. ${resource.sourceName}. ${resource.source}`} /></div><div className="detail-image"><Image src={resource.image} alt={`Polar landscape illustrating the ${resource.region} collection; not an expedition record`} fill sizes="(max-width: 800px) 100vw, 65vw" priority /></div>{resource.sample && <div className="notice"><strong>Sample learning article.</strong> This prototype copy has not undergone scientific review and is not an official NCPOR publication.</div>}<div className="article-body"><h2>{resource.type === 'Explainer' ? 'A starting point for curiosity' : 'About this resource'}</h2>{resource.body.map(p => <p key={p}>{p}</p>)}</div>{files.length>0&&<section className="attachment-editor"><h2>Reports & photographs</h2>{files.map(f=><figure className="attachment-card" key={f.id}>{f.mime.startsWith('image/')&&<img className="evidence-image" src={`/api/files/${f.id}?preview=1`} alt={f.attachment.alt} loading="lazy"/>}<figcaption><h3>{f.attachment.alt}</h3><p>Credit: {f.attachment.credit}<br/>Permission: {f.attachment.license}</p><a className="button button-outline" href={`/api/files/${f.id}`}>Download {f.mime==='application/pdf'?'PDF':'photo'}</a></figcaption></figure>)}</section>}</article><aside className="detail-meta"><h2>Connected to its source.</h2><dl><div><dt>Resource type</dt><dd>{resource.type}{resource.slug === 'polar-data-catalogue' ? ' discovery gateway' : ''}</dd></div><div><dt>Region</dt><dd>{resource.region}</dd></div><div><dt>Topic</dt><dd>{resource.topic}</dd></div><div><dt>{resource.slug === 'arctic-expedition-report' ? 'Report year' : 'Catalogue entry year'}</dt><dd>{resource.year}</dd></div><div><dt>Language</dt><dd>English</dd></div><div><dt>Source</dt><dd>{resource.sourceName}</dd></div><div><dt>Access</dt><dd>External reference. Original source terms apply.</dd></div></dl><a className="button button-dark" href={resource.source} target="_blank" rel="noreferrer">Open original source <ExternalLink size={15} /></a><p>Original source terms apply. Attached files, when available, are separately credited and reviewed. Landscape photography is illustrative; image credits are in About.</p></aside></div>{related.length > 0 && <section className="related-section"><p className="eyebrow">KEEP EXPLORING</p><h2>There’s more to the story.</h2><div className="resource-grid">{related.map((r, i) => <ResourceCard resource={r} index={i} key={r.slug} />)}</div></section>}</main>;
}
