'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowLeft,ArrowRight,BookOpen,Check,Feather,FileText,Languages,Plus,RefreshCw,ShieldCheck,Sparkles,Trash2,Download } from 'lucide-react';
import { formats,languages,type Source,type OutreachRow,type Content } from '@/lib/outreach-schema';
type User={id:string;name:string;role:string};
type Detail=OutreachRow&{events:{action:string;comment:string;created_at:string}[]};
async function api(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to complete the request.');return data;}
const blank=():Content=>({title:'',paragraphs:[{text:'',citations:[]}]});
const labels:Record<string,string>={draft:'Draft',in_review:'Awaiting review',changes_requested:'Changes requested',approved:'Approved',published:'Published',superseded:'Superseded',withdrawn:'Withdrawn'};
export function OutreachStudio(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [provider,setProvider]=useState('openai'),[providerLabel,setProviderLabel]=useState('OpenAI');
 const [sources,setSources]=useState<Source[]>([]),[drafts,setDrafts]=useState<OutreachRow[]>([]),[ready,setReady]=useState(false),[selected,setSelected]=useState<string[]>([]);
 const [content,setContent]=useState<Content>(blank),[format,setFormat]=useState<typeof formats[number]>('Student explainer'),[language,setLanguage]=useState<typeof languages[number]>('English');
 const [detail,setDetail]=useState<Detail|null>(null),[editing,setEditing]=useState(true),[generationId,setGenerationId]=useState<string|null>(null),[comment,setComment]=useState(''),[checked,setChecked]=useState(false),[languageChecked,setLanguageChecked]=useState(false),[dirty,setDirty]=useState(false);
 async function refresh(){const data=await api('/api/staff/outreach');setSources(data.sources);setDrafts(data.drafts);setReady(data.aiReady);setProvider(data.provider);setProviderLabel(data.providerLabel);}
 useEffect(()=>{(async()=>{try{const response=await fetch('/api/staff/me',{cache:'no-store'});if(response.status===401)return;if(!response.ok)throw new Error('Unable to open your staff session.');const data=await response.json();setUser(data.user);await refresh();}catch(e){setError((e as Error).message);}finally{setLoading(false);}})();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function open(id:string){const d=await api(`/api/staff/outreach/${id}`);setDetail(d);setContent({title:d.payload.title,paragraphs:d.payload.paragraphs});setFormat(d.payload.format);setLanguage(d.payload.language);setSelected(d.payload.sources.map((s:Source)=>s.revision_id));setGenerationId(d.payload.generationId);setEditing(false);setChecked(false);setLanguageChecked(false);setComment('');setDirty(false);}
 function fresh(){setDetail(null);setContent(blank());setSelected([]);setGenerationId(null);setEditing(true);setDirty(false);setError('');setMessage('');}
 async function act(action:string){if(!detail)return;await run(async()=>{await api(`/api/staff/outreach/${detail.id}`,'POST',{action,comment,evidenceChecked:checked,languageChecked});await open(detail.id);await refresh();setMessage(action==='publish'?'Your reviewed story is now public.':`Completed: ${action.replaceAll('_',' ')}.`);});}
 const evidence=editing?sources.filter(s=>selected.includes(s.revision_id)):(detail?.payload.sources??[]);
 const author=user?.role==='contributor';const editable=author&&editing;const chunks=evidence.flatMap(s=>s.chunks.map(c=>({...c,title:s.title})));
 const missing=content.paragraphs.some(p=>!p.citations.length||p.citations.some(id=>!chunks.some(c=>c.id===id)));
 const chars=content.paragraphs.map(p=>p.text).join('\n\n').length;
 if(loading)return <div className="container loading-state">Opening the studio…</div>;
 return <div className="container outreach-shell"><Link href="/workspace" className="text-link"><ArrowLeft size={15}/> Editorial workspace</Link>
 <header className="outreach-hero"><div><span className="eyebrow">THE OUTREACH STUDIO</span><h1>Cold frontiers.<br/><em>Warm conversations.</em></h1><p>Give polar science a voice people can connect with.<br/>Keep the evidence close, from the first word to the final review.</p></div><div className="studio-orbit" aria-hidden="true"><Feather size={45} strokeWidth={1}/><span>RESEARCH → UNDERSTANDING</span></div></header>
 <div className="studio-path"><span><BookOpen size={16}/>01 · Connect evidence</span><span><Feather size={16}/>02 · Shape your story</span><span><ShieldCheck size={16}/>03 · Review & release</span></div>
 {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="success-message" role="status">{message}</p>}
 {!user?<section className="workspace-panel studio-welcome"><Sparkles size={28}/><h2>Every good story starts with a source.</h2><p>Sign in with your staff account to choose published research, write in English or Hindi, and send your story for independent review.</p><Link className="button button-dark" href="/workspace">Sign in to the workspace <ArrowRight size={16}/></Link><p className="local-note">Student explainers · Website news · Social captions</p></section>:<>
 <div className="studio-topbar"><span className="prototype-badge">{user.role.toUpperCase()} · {user.name}</span><div><button disabled={busy||dirty} className="button button-outline" onClick={()=>void run(refresh)}><RefreshCw size={15}/>Refresh</button>{author&&<button disabled={busy||dirty} className="button button-dark" onClick={fresh}><Plus size={15}/>New story</button>}</div></div>
 <div className="outreach-grid"><aside className="outreach-evidence"><section className="workspace-panel"><span className="eyebrow">01 / YOUR EVIDENCE</span><h2>Start with what we know.</h2><p className="local-note">Approved catalogue text only. Linked websites and PDF contents are not read by this studio. Choose up to three sources.</p>
 {editable?sources.length?sources.map(s=><label className="source-option" key={s.revision_id}><input type="checkbox" disabled={busy||(!selected.includes(s.revision_id)&&selected.length>=3)} checked={selected.includes(s.revision_id)} onChange={()=>{setSelected(v=>v.includes(s.revision_id)?v.filter(x=>x!==s.revision_id):[...v,s.revision_id]);setGenerationId(null);setDirty(true);}}/><span>{s.title}<small>Revision {s.revision_no} · {s.cleared?'AI processing cleared':'Manual drafting available'}</small></span></label>):<p>No eligible published sources yet. Publish a report, dataset or publication in the editorial workspace first.</p>:null}
 {(user.role==='publisher'?sources:evidence).map(s=><details className="evidence-passage" key={s.revision_id} open={evidence.length===1}><summary>{s.title} <small>Revision {s.revision_no}</small></summary><a className="text-link" href={`/resources/${s.slug}`} target="_blank" rel="noreferrer">Open published source ↗</a>{s.chunks.map(c=><div key={c.id}><strong>{c.label}</strong><p>{c.text}</p></div>)}{user.role==='publisher'&&!s.cleared&&<><p className="local-note">Clear this public catalogue text only if its rights permit sending it to {providerLabel} for drafting.</p><button disabled={busy} className="button button-outline" onClick={()=>void run(async()=>{await api('/api/staff/outreach/clearance','POST',{revisionId:s.revision_id,provider});await refresh();setMessage(`This source revision is cleared for ${providerLabel} processing.`);})}>Clear for AI processing</button></>}</details>)}
 </section></aside>
 <section className="workspace-panel outreach-editor"><div className="studio-editor-top"><span className="eyebrow">02 / THE WRITING ROOM</span><span className={`status-label status-${detail?.status??'draft'}`}>{detail?`${labels[detail.status]} · v${detail.version}`:'New draft'}</span></div><h2>{editable?'Make science feel closer.':detail?'A story, with its evidence.':'Choose a story to review.'}</h2>
 {!ready&&<div className="studio-provider-note"><Sparkles size={18}/><span><strong>{providerLabel} is not connected yet.</strong> Manual writing, saving and review are available.</span></div>}
 {detail&&!detail.eligible&&<p className="error-message">A source has changed or been withdrawn. This story cannot be released or exported. Its author must select current sources and save a new revision.</p>}
 {(author||detail)&&<><fieldset disabled={!editable||busy} className="studio-fields"><div className="form-grid"><div className="field"><label htmlFor="outreach-format">Content format</label><select id="outreach-format" value={format} onChange={e=>{setFormat(e.target.value as typeof format);setDirty(true);setGenerationId(null);}}>{formats.map(f=><option key={f}>{f}</option>)}</select></div><div className="field"><label htmlFor="outreach-language"><Languages size={14}/> Writing language</label><select id="outreach-language" value={language} onChange={e=>{setLanguage(e.target.value as typeof language);setDirty(true);setGenerationId(null);}}>{languages.map(l=><option key={l}>{l}</option>)}</select></div></div></fieldset>
 {editable&&<div className="studio-generation"><button className="button button-dark" disabled={busy||!ready||!selected.length||evidence.some(s=>!s.cleared)||!!content.title||content.paragraphs.some(p=>p.text)} onClick={()=>void run(async()=>{const result=await api('/api/staff/outreach/generate','POST',{sourceIds:selected,format,language});setContent({title:result.title,paragraphs:result.paragraphs});setGenerationId(result.generationId);setDirty(true);setMessage('AI draft ready. Check every claim against its evidence before saving.');})}><Sparkles size={16}/>{busy?'Working…':'Draft with AI'}</button><small>{content.title||content.paragraphs.some(p=>p.text)?'Start a new story to generate without replacing your writing.':`Only publisher-cleared public text is sent to ${providerLabel}.`}</small></div>}
 <fieldset disabled={!editable||busy} className="studio-fields"><div className="field"><label htmlFor="outreach-title">Story title</label><input id="outreach-title" lang={language==='Hindi'?'hi':'en'} value={content.title} maxLength={180} placeholder="An invitation to discover something new" onChange={e=>{setContent({...content,title:e.target.value});setDirty(true);}}/></div>
 {content.paragraphs.map((p,i)=><div className="outreach-paragraph" key={i}><div className="paragraph-heading"><label htmlFor={`paragraph-${i}`}>Passage {String(i+1).padStart(2,'0')}</label>{editable&&content.paragraphs.length>1&&<button type="button" aria-label={`Remove passage ${i+1}`} onClick={()=>{setContent({...content,paragraphs:content.paragraphs.filter((_,n)=>n!==i)});setDirty(true);}}><Trash2 size={15}/></button>}</div><textarea id={`paragraph-${i}`} lang={language==='Hindi'?'hi':'en'} value={p.text} maxLength={2500} placeholder={language==='Hindi'?'विज्ञान की कहानी सरल शब्दों में लिखें…':'Start with a question. Explain one idea. Keep the wonder.'} onChange={e=>{setContent({...content,paragraphs:content.paragraphs.map((x,n)=>n===i?{...x,text:e.target.value}:x)});setDirty(true);}}/><div className="citation-picker"><span><BookOpen size={13}/> Supporting evidence</span>{chunks.map(c=><label key={c.id}><input type="checkbox" checked={p.citations.includes(c.id)} onChange={()=>{setContent({...content,paragraphs:content.paragraphs.map((x,n)=>n===i?{...x,citations:x.citations.includes(c.id)?x.citations.filter(id=>id!==c.id):[...x.citations,c.id]}:x)});setDirty(true);}}/>{c.title} · {c.label}</label>)}{!chunks.length&&<small>Select a source to connect a supporting passage.</small>}{p.citations.some(id=>!chunks.some(c=>c.id===id))&&<button type="button" className="text-link" onClick={()=>{setContent({...content,paragraphs:content.paragraphs.map((x,n)=>n===i?{...x,citations:x.citations.filter(id=>chunks.some(c=>c.id===id))}:x)});setDirty(true);}}>Remove outdated citations</button>}</div></div>)}
 {editable&&content.paragraphs.length<12&&<button type="button" className="text-link" onClick={()=>{setContent({...content,paragraphs:[...content.paragraphs,{text:'',citations:[]}]});setDirty(true);}}><Plus size={15}/>Add passage</button>}</fieldset>
 <div className="studio-wordcount"><span>{chars} characters{format==='Social caption'?' / 600':''}</span><span>{missing?'Evidence needs attention':'Evidence linked · human check required'}</span></div>
 {editable?<div className="form-actions"><button disabled={busy||!selected.length||missing||content.title.trim().length<5||content.paragraphs.some(p=>p.text.trim().length<10)} className="button button-dark" onClick={()=>void run(async()=>{const result=await api('/api/staff/outreach','POST',{...content,format,language,sourceIds:selected,previousId:detail?.id??null,generationId});await open(result.id);await refresh();setMessage('Draft saved. Independent review is required before publication.');})}><Check size={16}/>Save draft</button>{dirty&&<button disabled={busy} className="button button-outline" onClick={()=>{if(detail)void run(()=>open(detail.id));else fresh();}}>Discard unsaved edits</button>}</div>:detail&&<div className="studio-review"><span className="eyebrow">03 / REVIEW & RELEASE</span>{author&&<div className="form-actions"><button disabled={busy||detail.status==='in_review'} className="button button-outline" onClick={()=>{setEditing(true);setSelected(detail.payload.sources.map(s=>s.revision_id));setGenerationId(null);}}>Edit as new revision</button>{detail.status==='draft'&&<button disabled={busy||!detail.eligible} className="button button-dark" onClick={()=>void act('submit')}>Send for review <ArrowRight size={15}/></button>}</div>}
 {user.role==='reviewer'&&detail.status==='in_review'&&<><label className="attachment-consent"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I checked the title and every factual claim against the selected evidence, including unsupported statements and uncertainty.</label><label className="attachment-consent"><input type="checkbox" checked={languageChecked} onChange={e=>setLanguageChecked(e.target.checked)}/>I checked the {language} wording and scientific terminology.</label></>}
 {(user.role==='reviewer'||user.role==='publisher')&&<div className="field"><label htmlFor="outreach-comment">Review note / withdrawal reason</label><textarea id="outreach-comment" value={comment} maxLength={2000} onChange={e=>setComment(e.target.value)}/></div>}
 <div className="form-actions">{user.role==='reviewer'&&detail.status==='in_review'&&<><button disabled={busy||!checked||!languageChecked||!detail.eligible} className="button button-dark" onClick={()=>void act('approve')}>Approve this revision</button><button disabled={busy||!comment.trim()} className="button button-outline" onClick={()=>void act('request_changes')}>Request changes</button></>}{user.role==='publisher'&&detail.status==='approved'&&<button disabled={busy||!detail.eligible} className="button button-dark" onClick={()=>void act('publish')}>Publish reviewed story</button>}{user.role==='publisher'&&detail.status==='published'&&<button disabled={busy||!comment.trim()} className="button button-outline" onClick={()=>void act('withdraw')}>Withdraw</button>}{detail.status==='published'&&detail.eligible&&<><Link className="button button-outline" href={`/outreach/${detail.id}`}>View story ↗</Link><a className="button button-outline" href={`/api/staff/outreach/${detail.id}/export`}><Download size={15}/>Export reviewed copy</a></>}</div>
 {!!detail.events.length&&<details className="studio-history"><summary>Revision history</summary>{detail.events.map((e,i)=><p key={i}><strong>{e.action.replaceAll('_',' ')}</strong> · {new Date(e.created_at).toLocaleString()}<br/>{e.comment}</p>)}</details>}</div>}</>}
 </section></div>
 <section className="studio-draft-shelf"><div><span className="eyebrow">STORIES IN PROGRESS</span><h2>Your next conversation.</h2></div><div className="studio-draft-grid">{drafts.length?drafts.map(d=><button key={d.id} disabled={busy||dirty} className={`studio-draft-card ${detail?.id===d.id?'selected':''}`} onClick={()=>void run(()=>open(d.id))}><span className={`status-label status-${d.status}`}>{labels[d.status]}</span><strong>{d.payload.title}</strong><small>{d.payload.format} · {d.payload.language} · v{d.version}</small>{!d.eligible&&<small>Source needs updating</small>}<ArrowRight size={16}/></button>):<div className="studio-no-drafts"><FileText size={26}/><p>Stories saved here will be ready for their next step.</p></div>}</div></section>
 </> }</div>;
}
