'use client';

import { useState, useEffect } from 'react';
import { LayoutDashboard, FilePlus2, PenLine, FolderOpen, ArrowRight, FileText, ExternalLink, Download, Check } from 'lucide-react';
import { resources } from '@/lib/data';

type Draft = { id: string; title: string; body: string; kind: string; sources: string[]; updatedAt: string };
const storageKey = 'polarbridge-local-drafts-v1';
const tabs = [{ key: 'overview', label: 'Overview', icon: LayoutDashboard }, { key: 'catalogue', label: 'Catalogue a reference', icon: FilePlus2 }, { key: 'studio', label: 'Outreach studio', icon: PenLine }, { key: 'drafts', label: 'My local drafts', icon: FolderOpen }];

export function Workspace() {
  const [tab, setTab] = useState('overview');
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [ready, setReady] = useState(false);
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');
  const [kind, setKind] = useState('Article');
  const [selected, setSelected] = useState<string[]>([]);
  const [editing, setEditing] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { try { const value: unknown = JSON.parse(localStorage.getItem(storageKey) || '[]'); if (Array.isArray(value)) setDrafts(value.filter((d): d is Draft => typeof d?.id === 'string' && typeof d?.title === 'string' && typeof d?.body === 'string' && typeof d?.kind === 'string' && typeof d?.updatedAt === 'string' && Array.isArray(d?.sources) && d.sources.every((s: unknown) => typeof s === 'string'))); } catch { setError('Local drafts could not be read. You can still write and export a new draft.'); } setReady(true); }, []);
  function changeTab(next: string) { setTab(next); setMessage(''); setError(''); }
  function saveDraft(draft: Draft) { const next = [draft, ...drafts.filter(d => d.id !== draft.id)]; try { localStorage.setItem(storageKey, JSON.stringify(next)); setDrafts(next); setMessage('Draft saved on this browser. It has not been submitted or published.'); setError(''); return true; } catch { setError('Browser storage is unavailable. Export your draft to keep a copy.'); return false; } }
  function saveArticle() { if (!title.trim() || !body.trim()) { setError('Add a title and some text before saving.'); setMessage(''); return; } const id = editing || crypto.randomUUID(); if (saveDraft({ id, title: title.trim(), body, kind, sources: selected, updatedAt: new Date().toISOString() })) setEditing(id); }
  function editDraft(d: Draft) { setEditing(d.id); setTitle(d.title); setBody(d.body); setKind(d.kind); setSelected(d.sources); changeTab('studio'); }
  function exportDraft() { if (!title.trim() || !body.trim()) { setError('Add a title and some text before exporting.'); return; } const citations = selected.map(slug => resources.find(r => r.slug === slug)).filter(Boolean).map(r => `- ${r!.title}: ${r!.source}`).join('\n'); const text = `# ${title}\n\nLocal draft — not reviewed or published\n\n${body}\n\n## Sources\n${citations || 'No sources attached.'}\n`; const url = URL.createObjectURL(new Blob([text], { type: 'text/markdown;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'polarbridge-draft.md'; link.click(); URL.revokeObjectURL(url); setError(''); setMessage('Unreviewed draft exported.'); }
  return <div className="workspace-shell container"><div className="workspace-heading"><div><p className="eyebrow">FROM RESEARCH TO UNDERSTANDING</p><h1>A place for your next story.</h1><p>Connect a source. Shape an idea. Make science easier to understand.</p></div><span className="prototype-badge">LOCAL WORKSPACE PREVIEW</span></div><div className="notice">Try the editorial experience with public references. Drafts stay in this browser; this preview has no sign-in, file uploads, AI generation, review or publication service.</div><div className="workspace-tabs" role="tablist" aria-label="Workspace sections">{tabs.map(({ key, label, icon: Icon }) => <button key={key} role="tab" id={`tab-${key}`} aria-selected={tab === key} aria-controls={`panel-${key}`} onClick={() => changeTab(key)}><Icon size={16} />{label}</button>)}</div><div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
    {tab === 'overview' && <div className="workspace-overview"><section className="workspace-panel"><h2>A thoughtful path to public understanding.</h2><p>Start with a reference and try writing an outreach draft. The full publication workflow is designed around human review.</p><div className="workflow-steps">{[['Connect the research', 'Keep the original source close to the story.'], ['Write for your audience', 'Explain the idea in language your reader understands.'], ['Review before release', 'Scientific review and publishing will be enabled with the backend.']].map(([t, d], i) => <div className="workflow-step" key={t}><span>0{i + 1}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><button className="button button-dark" onClick={() => changeTab('studio')}>Start an outreach draft <ArrowRight size={16} /></button></section><section className="workspace-panel"><span className="eyebrow">ON THIS DEVICE</span><h2>Your ideas, kept close.</h2>{drafts.length ? <div className="draft-list">{drafts.slice(0, 3).map(d => <div className="draft-item" key={d.id}><div><h3>{d.title}</h3><small>{d.kind} · Local draft</small></div><button onClick={() => editDraft(d)}>Open</button></div>)}</div> : <div className="workspace-empty"><FolderOpen size={35} strokeWidth={1.2} /><h3>A fresh page awaits.</h3><p>Your saved drafts will appear here.<br />Start with a question worth sharing.</p></div>}<p className="local-note">Browser storage is device-specific. Export important work before clearing browser data or switching devices.</p></section></div>}
    {tab === 'catalogue' && <section className="workspace-panel"><span className="eyebrow">ADD CONTEXT, KEEP THE SOURCE</span><h2>Catalogue a public reference.</h2><p>Save a local catalogue draft. Nothing is uploaded or added to the public collection.</p><form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const source = String(data.get('source')); try { const url = new URL(source); if (!['https:', 'http:'].includes(url.protocol)) throw new Error(); } catch { setError('Enter a valid https:// or http:// source URL.'); return; } const saved = saveDraft({ id: crypto.randomUUID(), title: String(data.get('title')).trim(), body: `${String(data.get('summary')).trim()}\n\nOriginal reference: ${source}\nRights: ${data.get('rights')}\nRegion: ${data.get('region')}`, kind: String(data.get('type')), sources: [], updatedAt: new Date().toISOString() }); if (saved) e.currentTarget.reset(); }}><div className="form-grid"><div className="field full"><label htmlFor="reference-title">Resource title</label><input id="reference-title" name="title" required maxLength={180} placeholder="Give this reference a clear, descriptive title" /></div><div className="field"><label htmlFor="reference-type">Resource type</label><select id="reference-type" name="type"><option>Report</option><option>Dataset</option><option>Publication</option></select></div><div className="field"><label htmlFor="reference-region">Polar region</label><select id="reference-region" name="region"><option>Antarctica</option><option>Arctic</option><option>Southern Ocean</option></select></div><div className="field full"><label htmlFor="reference-url">Original source URL</label><input id="reference-url" name="source" type="url" required placeholder="https://" /><small>Link to the original publisher. Files are not copied into this preview.</small></div><div className="field full"><label htmlFor="reference-summary">Short description</label><textarea id="reference-summary" name="summary" required maxLength={3000} placeholder="What can a reader discover in this resource?" /></div><div className="field full"><label htmlFor="reference-rights">Rights information</label><select id="reference-rights" name="rights"><option>External reference only</option><option>Rights unknown — requires review</option><option>Permission documented — requires verification</option></select></div></div><div className="form-actions"><button disabled={!ready} className="button button-dark" type="submit">Save local reference <Check size={16} /></button></div></form></section>}
    {tab === 'studio' && <div className="studio-layout"><section className="workspace-panel studio-sources"><h2>Start with a source.</h2>{resources.filter(r => !r.sample).map(r => <label className="source-option" key={r.slug}><input type="checkbox" checked={selected.includes(r.slug)} onChange={() => setSelected(selected.includes(r.slug) ? selected.filter(s => s !== r.slug) : [...selected, r.slug])} /><span>{r.title}<small>{r.type} · {r.region}</small></span></label>)}</section><section className="workspace-panel"><span className="eyebrow">OUTREACH STUDIO · MANUAL DRAFT</span><h2>Make room for an idea.</h2><div className="form-grid"><div className="field"><label htmlFor="draft-kind">Content format</label><select id="draft-kind" value={kind} onChange={e => setKind(e.target.value)}>{['Article', 'Student explainer', 'Social caption', 'Report', 'Dataset', 'Publication'].map(k => <option key={k}>{k}</option>)}</select></div><div className="field"><label htmlFor="draft-title">Title</label><input id="draft-title" value={title} onChange={e => setTitle(e.target.value)} maxLength={180} placeholder="A title that invites curiosity" /></div><div className="field full"><label htmlFor="draft-body">Your story</label><textarea className="editor-area" id="draft-body" value={body} onChange={e => setBody(e.target.value)} maxLength={30000} placeholder="Start with the question. Explain the idea. Keep your sources close.&#10;&#10;This is your writing space — AI generation will be connected in a later build." /><small>{body.trim() ? body.trim().split(/\s+/).length : 0} words · Unreviewed draft</small></div></div>{selected.length > 0 && <div className="studio-evidence"><h3>References beside your story</h3>{selected.map(slug => { const r = resources.find(item => item.slug === slug); return r ? <a href={r.source} key={slug} target="_blank" rel="noreferrer">{r.title} <ExternalLink size={13} /></a> : null; })}<p className="local-note">Selecting a reference does not verify a claim. Check every scientific statement against the original source.</p></div>}<div className="form-actions"><button className="button button-dark" disabled={!ready} onClick={saveArticle}>Save local draft <Check size={16} /></button><button className="button button-outline" onClick={exportDraft}>Export draft <Download size={16} /></button></div></section></div>}
    {tab === 'drafts' && <section className="workspace-panel"><h2>Ideas in progress.</h2><p>{drafts.length} saved {drafts.length === 1 ? 'draft' : 'drafts'} on this browser.</p>{drafts.length ? <div className="draft-list">{drafts.map(d => <div className="draft-item" key={d.id}><FileText size={20} /><div style={{ flex: 1 }}><h3>{d.title}</h3><small>{d.kind} · Saved {new Date(d.updatedAt).toLocaleDateString('en-GB')} · Not reviewed</small></div><button onClick={() => editDraft(d)}>Open draft</button></div>)}</div> : <div className="workspace-empty"><FolderOpen size={35} strokeWidth={1.2} /><h3>No drafts yet.</h3><p>Save a reference or start writing in the outreach studio.</p><button className="button button-dark" onClick={() => changeTab('studio')}>Start writing <ArrowRight size={16} /></button></div>}</section>}
    </div>{message && <p className="success-message" role="status" style={{ marginTop: 20 }}>{message}</p>}{error && <p className="error-message" role="alert" style={{ marginTop: 20 }}>{error}</p>}</div>;
}
